const categoriesAndElements: Record<string, string[]> = {
    drum: ["Kick In", 
        "Kick Out", 
        "kick Triggered", 
        "Snare Top", 
        "Snare Bottom", 
        "Snare Triggered", 
        "Tom high", 
        "Tom Mid", 
        "Tom Floor", 
        "Tom Triggered", 
        "hit Hat", 
        "Cymbal", 
        "Overhead Left", 
        "Overhead Center", 
        "Overhead Right", 
        "UnderHead Left", 
        "Underhead Right"],
    percussions: ["Congas", 
        "Bongos", 
        "Djembe", 
        "Darbouka", 
        "Cajon", 
        "Tambour", 
        "Gong", 
        "Tambourin", 
        "Cymbale", 
        "Xilophone", 
        "Marimba", 
        "Vibraphone", 
        "Glockenspiel", 
        "Timbale", 
        "Gong", 
        "Triangle", 
        "Shime"],
    bass: ["Contrebasse", 
        "Basse Acoustique", 
        "Basse Electro-Acoustique", 
        "Basse Electrique"],
    guitar: ["Guitare Acoustique", 
        "Guitare Electro-acoustique", 
        "Guitare Electrique"],
    string: ["Ukulele", 
        "banjo", 
        "Mandoline", 
        "Lapsteel", 
        "PedalSteel", 
        "Luth", 
        "Oud", 
        "Cithare", 
        "Harpe", 
        "Violon Acoustique", 
        "Violon Electrique", 
        "Alto Acoustique", 
        "Alto Electrique", 
        "Violoncelle Acoustique", 
        "Violoncelle Electrique", 
        "Viole de Gambe", 
        "Vielle à Roue"],
    wind: ["Trompette", 
        "Trombone à Pistons", 
        "Trombone à Coulisse", 
        "Saxophone", 
        "Tuba", 
        "Cornet", 
        "Basson", 
        "Baryton", 
        "Cor Anglais", 
        "Didgeridoo", 
        "Cornet", 
        "Flûte Traversière", 
        "Flûte à Bec", 
        "Flûte à anche Double", 
        "Flûte de Pan", 
        "HautBois", 
        "Ocarina", 
        "Clarinette"],
    keyboards: ["Piano Droit", 
        "Piano à Queue", 
        "Piano Electrique", 
        "Piano Numérique", 
        "Clavier Arrangeur", 
        "Workstation"],
    numeric: ["Batterie Electronique Left", 
        "batterie Electronique Right", 
        "Sampler", 
        "Samplepad", 
        "laptop", 
        "mobile"],
    vocals: ["Micro Filaire", 
        "Micro Sans Fil", 
        "Micro HeadSet Sans fil"],
  };

export default categoriesAndElements;