export const Items = {
  Outputs: {
    Speakers: ["Wedge", "Wedge x2", "Side left", "Side Right"],
    EarPhones: ["Oreillettes In-Ears", "casque Headset"],
  },
  Inputs: {
    Percussions: [
      "Batterie Acoustique",
      "Batterie Electronique",
      "Congas",
      "Bongos",
      "Djembe",
      "Darbouka",
      "Cajon",
      "Tambour",
      "Gong",
      "Tambourin",
      "Cymbale",
      "Xilophone",
      "Marimba",
      "Vibraphone",
      "Glockenspiel",
      "Timbale",
      "Gong",
      "Triangle",
      "Shime",
    ],
    Bass: [
      "Contrebasse",
      "Basse Acoustique",
      "Basse Electro-Acoustique",
      "Basse Electrique",
    ],
    Guitar: [
      "Guitare Acoustique",
      "Guitare Electro-acoustique",
      "Guitare Electrique",
    ],
    Picked: [
      "Ukulele",
      "banjo",
      "Mandoline",
      "Lapsteel",
      "PedalSteel",
      "Luth",
      "Oud",
      "Cithare",
      "Harpe",
      "",
    ],
    Bowed: [
      "Violon Acoustique",
      "Violon Electrique",
      "Alto Acoustique",
      "Alto Electrique",
      "Violoncelle Acoustique",
      "Violoncelle Electrique",
      "Viole de Gambe",
      "Vielle à Roue",
    ],
    Brass: [
      "Trompette",
      "Trombone à Pistons",
      "Trombone à Coulisse",
      "Saxophone",
      "Tuba",
      "Cornet",
      "Basson",
      "Baryton",
      "Cor Anglais",
      "Didgeridoo",
      "Cornet",
    ],
    WoodWind: [
      "Flûte Traversière",
      "Flûte à Bec",
      "Flûte à anche Double",
      "Flûte de Pan",
      "HautBois",
      "Ocarina",
      "Clarinette",
    ],
    Electro: {
      Keyboards: [
        "Piano Droit",
        "Piano à Queue",
        "Piano Electrique",
        "Piano Numérique",
        "Clavier Arrangeur",
        "Workstation",
      ],
      Pads: ["Sampler", "Samplepad"],
      Computer: ["laptop", "mobile"],
    },
    Vocals: ["Micro Filaire", "Micro Sans Fil", "Micro HeadSet Sans fil"],
    Amps: [
      "Combo 1x12",
      "Combo 2x12",
      "Combo 1x15",
      "Combo 1x18",
      "Head + 1x10",
      "Head + 1x12",
      "Head + 2x10",
      "Head + 2x12",
      "Head + 4x10",
      "Head + 4x12",
      "Head + 1x15",
      "Head + 1x18",
      "Head + 8x10",
      "Head + 4x12 + 4x12",
      "Head + 4x12 + 1x18",
    ],
    Speakers: ["1x10", "1x12", "2x10", "2x12", "4x10", "4x12", "8x10", "8x12"],
    PedalBoard: ["Effect", "Effect + Amp"],
  },
  ALim: ["usb", "alimentation électrique"],
};
